// gen-dates.mjs — pre-build script
// Derives the "last updated" date of every content file from git history,
// so a static site knows when each article changed without manual bookkeeping.
//
//   git log -1 --format=%cs -- <file>   →   YYYY-MM-DD of last commit touching it
//
// Output: src/generated/dates.js  →  export default { 'blog/x': '2026-08-07', ... }
// Frontmatter `date` in a file still wins as the publish date.

import { execSync } from 'child_process'
import { readdirSync, statSync, writeFileSync, mkdirSync } from 'fs'
import { join, relative } from 'path'

const root = process.cwd()
const contentDir = join(root, 'content')
const outDir = join(root, 'src', 'generated')

function walk(dir) {
  const results = []
  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    const st = statSync(full)
    if (st.isDirectory()) {
      results.push(...walk(full))
    } else if (/\.(md|vue)$/.test(name)) {
      results.push(full)
    }
  }
  return results
}

function gitDate(relPath) {
  try {
    // relPath is relative to content/; git needs it relative to repo root
    const gitPath = `content/${relPath}`
    const out = execSync(`git log -1 --format=%cs -- ${gitPath}`, {
      cwd: root,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore']
    }).trim()
    return out || ''
  } catch {
    return ''
  }
}

const dates = {}
for (const file of walk(contentDir)) {
  const rel = relative(contentDir, file).replace(/\\/g, '/')
  const d = gitDate(rel)
  if (d) dates[rel] = d
}

mkdirSync(outDir, { recursive: true })
const body =
  '// Auto-generated by scripts/gen-dates.mjs — DO NOT EDIT.\n' +
  'export default ' +
  JSON.stringify(dates, null, 2) +
  '\n'
writeFileSync(join(outDir, 'dates.js'), body)
console.log(`gen-dates: wrote ${Object.keys(dates).length} dates → src/generated/dates.js`)