name: Pages

on:
  push:
    branches:
      - main # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Restore file creation time
        run: |
          git ls-files -z | while read -d '' path; do
            first_commit_time=$(git log --diff-filter=A --format="%at" -- "$path" | head -n 1)
            if [ -n "$first_commit_time" ]; then
              touch -d "@$first_commit_time" "$path"
            fi
          done
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public